x=2500
while [ $x -le 10000 ]
do
n=$(lsof -iTCP:$x)
  if [ "$n" == "" ]
then
    break
fi
  x=$(( $x + 1 ))
done
echo $x
port=$x

(./Programs/serverbyte.py $1 $port &)  && (echo "Server Started on port " $port) && (echo "Sending Byte Array to Client") && ( sleep 0.5) && (./Programs/clientbyte.py $port) && (echo "byte-IR Generated by Client") && (./Programs/bytetoinput.py > byte-Output) && (echo "byte-Output Generated by Client after unmarshalling byte-IR") 

x=10001
while [ $x -le 50000 ]
do
n=$(lsof -iTCP:$x)
  if [ "$n" == "" ]
then
    break
fi
  x=$(( $x + 1 ))
done
echo $x
port=$x
(echo "Starting Server for XML Representation") && (port=$(($RANDOM%63000+2001))) && (./Programs/serverxml.py $1 $port &)  && (echo "Server Started on port " $port) && (echo "Sending XML Byte Array to Client") && ( sleep 0.5) && (./Programs/clientxml.py $port) && (echo "XML-IR Generated by Client") && (./Programs/parsexmltoinput.py > xml-Output) && (echo "XML-Output Generated by Client after unmarshalling XML-IR")  



